---
- hosts: all
  sudo: yes

  tasks:

    - name: Run 'apt-get update'
      apt: update_cache=yes

    - name: Install needed packages
      apt: pkg={{ item }} state=latest
      with_items:
        - vim
        - git
        - curl
        - make
        - libfile-slurp-perl
        - python-pycurl
        - dpkg-dev
        - devscripts
        - debhelper
