#!/bin/bash

PROJECT_DIR=/opt/carpc

# создавать пользователя
/usr/sbin/useradd carpc;

# актуальный virtualenv
/usr/bin/easy_install virtualenv

# инсталляция/обновление виртуального окружения
if [ ! -d "/opt/carpc/backend/virt_env/" ]; then
    mkdir /opt/carpc/backend/virt_env/;
    virtualenv --system-site-packages /opt/carpc/backend/virt_env/
fi

# первая установка
if [ ! -f "/$PROJECT_DIR/backend/project/settings.py" ]; then

    # устанавливаем конфиг
    cp $PROJECT_DIR/backend/project/settings_example.py $PROJECT_DIR/backend/project/settings.py
fi

apt-get install streamer vlc nodejs
npm install bower -g

cd $PROJECT_DIR/backend/
virt_env/bin/activate install -r requirements.txt
virt_env/bin/python manage.py syncdb --noinput
virt_env/bin/python manage.py migrate
virt_env/bin/python manage.py loaddata obd_sensors
cd ../frontend
bower install

cd $PROJECT_DIR/backend/
# права на конфиг
/bin/chown -R carpc:carpc /opt/carpc/
/bin/chmod a-r project/settings.py
/bin/chmod u+r project/settings.py
/bin/chmod a+x /etc/init.d/carpc.init


# перезапустим процесс
/etc/init.d/carpc.init stop
/etc/init.d/carpc.init start
# автозагрузка
#update-rc.d carpc.init defaults 98 02
