#!/bin/bash

PROJECT_DIR=/opt/carpc

/usr/sbin/useradd carpc;
/usr/bin/easy_install virtualenv

# update virtualenv
if [ ! -d "/opt/carpc/backend/virt_env/" ]; then
    mkdir /opt/carpc/backend/virt_env/;
    virtualenv --system-site-packages /opt/carpc/backend/virt_env/
fi

cd $PROJECT_DIR/backend/
virt_env/bin/activate install -r requirements.txt
virt_env/bin/python manage.py syncdb --noinput
virt_env/bin/python manage.py migrate
virt_env/bin/python manage.py loaddata obd_sensors

cd ../frontend
npm install bower -g
bower install


# permissions
/bin/chown -R carpc:carpc /opt/carpc/
/bin/chown -R carpc:carpc /etc/carpc/
/bin/chmod a-r /etc/carpc/settings.py
/bin/chmod u+r /etc/carpc/settings.py
/bin/chmod a+x /etc/init.d/carpc.init


# restart
/etc/init.d/carpc.init stop
/etc/init.d/carpc.init start
