Document: carpc
Title: Debian carpc Manual
Author: <insert document author here>
Abstract: This manual describes what carpc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/carpc/carpc.sgml.gz

Format: postscript
Files: /usr/share/doc/carpc/carpc.ps.gz

Format: text
Files: /usr/share/doc/carpc/carpc.text.gz

Format: HTML
Index: /usr/share/doc/carpc/html/index.html
Files: /usr/share/doc/carpc/html/*.html
