#!/bin/bash

/usr/sbin/useradd carpc

/usr/bin/easy_install virtualenv

# create virtualenv
if [ ! -d "/opt/carpc/backend/virt_env/" ]; then
    /bin/mkdir -p /opt/carpc/backend/virt_env/;
    /usr/local/bin/virtualenv --system-site-packages /opt/carpc/backend/virt_env/
fi

cd /opt/carpc/backend
virt_env/bin/pip install -r requirements.txt
ln -s /etc/carpc/settings.py project/settings.py
virt_env/bin/python manage.py syncdb --noinput
virt_env/bin/python manage.py migrate
virt_env/bin/python manage.py loaddata obd_sensors


# permissions
/bin/chown -R carpc:carpc /opt/carpc/
/bin/chown -R carpc:carpc /etc/carpc/
/bin/chmod a-r /etc/carpc/settings.py
/bin/chmod u+r /etc/carpc/settings.py
/bin/chmod a+x /etc/init.d/carpc

# restart
/etc/init.d/carpc stop
/etc/init.d/carpc start

# nginx
rm /etc/nginx/sites-enabled/default
/bin/chown -R www-data:www-data /var/log/carpc
/etc/init.d/nginx restart

# directory for cyncin. May be via dropbox or etc.
/bin/mkdir -p /opt/carpc/sync/movie_input